name: Push Stable Branch
on:
  pull_request:
    types: [closed] 
    branches:
      - stable
jobs:
  report:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Pull request merged
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/stable:refs/remotes/origin/stable
          git checkout -b stable origin/stable
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: stable-to-master
